name: Project4-work-flow
on: 
  push:
    branches: [main]
    workflow-dispatch:
    tags:
      - "v*.*.*"
jobs:
  Prj4-workflow:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Project 4 WF"
      - uses: actions/checkout@v2
      - run: ls
#      - docker login -u weichen66 -pass wait
      - run: echo "Done"
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          echo "$SUPER_SECRET" 
      - name: Collecting tag
        id: mata
        uses: docker/metadata-action@v4
        with: 
          images: |
            weichen66/ceg3120
          tags: |
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
            #tags: weichen66/ceg3120:latest
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
