name: Project4-work-flow
on: 
  push:
    branches: [main]
    workflow-dispatch:
jobs:
  Prj4-workflow:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Project 4"
      - uses: actions/checkout@v2
      - run: ls
#      - docker login -u weichen66 -pass wait
      - run: echo "Done"
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          echo "$SUPER_SECRET"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: user/app:latest
